name: Deploy CodyUs

on:
  pull_request:
    branches:
      - main
    types:
      - closed # PR이 닫히거나 병합될 때만 실행

jobs:
  deploy:
    name: Rolling Deploy to EC2
    if: github.event.pull_request.merged == true #병합된 경우에만 실행
    runs-on: ubuntu-latest

    steps:
    # 1. Git 저장소 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Gradle 빌드 
    - name: Build with Gradle
      run: ./gradlew clean build

    # 3. 첫 번째 EC2 서버로 JAR 파일 업로드 및 배포
    - name: Upload and Deploy to EC2 Instance 1
      uses: appleboy/scp-action@v0.1.3  # SCP를 통해 JAR 파일 업로드
      with:
        host: ${{ secrets.EC2_HOST_1 }}  # 첫 번째 EC2 인스턴스
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        source: ./build/libs/eCommerce-0.0.1-SNAPSHOT.jar
        target: /home/ubuntu/

    - name: Execute commands on EC2 Instance 1
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST_1 }}  # 첫 번째 EC2 인스턴스
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          # 실행 중인 애플리케이션 종료
          if sudo lsof -i :8080; then
            echo "Stopping app running on port 8080..."
            sudo kill -9 $(sudo lsof -t -i :8080)
          fi

          # 새 애플리케이션 실행
          cd /home/ubuntu
          nohup java -jar eCommerce-0.0.1-SNAPSHOT.jar &

    # 4. 첫 번째 EC2의 애플리케이션이 실행 중인지 확인 (Health Check) 
    - name: Wait for EC2 Instance 1 to become healthy
      run: |
        echo "Checking if instance 1 is healthy..."
        for i in {1..30}; do  # 최대 30번(5분)까지 확인 시도
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.EC2_1_HEALTH_CHECK_URL }})
          if [ "$response" -eq 200 ]; then
            echo "Instance 1 is healthy!"
            break
          fi
          echo "Instance 1 is not ready yet... retrying in 10 seconds."
          sleep 10
        done
      shell: bash

    # 5. 두 번째 EC2 서버로 JAR 파일 업로드 및 배포
    - name: Upload and Deploy to EC2 Instance 2
      uses: appleboy/scp-action@v0.1.3  # SCP를 통해 JAR 파일 업로드
      with:
        host: ${{ secrets.EC2_HOST_2 }}  # 두 번째 EC2 인스턴스
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        source: ./build/libs/eCommerce-0.0.1-SNAPSHOT.jar
        target: /home/ubuntu/

    - name: Execute commands on EC2 Instance 2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST_2 }}  # 두 번째 EC2 인스턴스
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          # 실행 중인 애플리케이션 종료
          if sudo lsof -i :8080; then
            echo "Stopping app running on port 8080..."
            sudo kill -9 $(sudo lsof -t -i :8080)
          fi

          # 새 애플리케이션 실행
          cd /home/ubuntu
          nohup java -jar eCommerce-0.0.1-SNAPSHOT.jar &
